### ISSUE TITLE
ffmpeg调用mediacodec硬编码出现绿边

### ISSUE THREAD

**Issue by zhubinsheng** [quink-black/ffmpeg-faq#2]
1080p的输出，但是最后边出现了一条绿边，如果是1088x1920则不会出现
![image](https://user-images.githubusercontent.com/44765143/225227044-3bb801ff-2570-4872-90de-b7aaeb4548c8.png)
，

**Comment by zhubinsheng** [comment]
感谢作者的提交 不知道为什么会这样

**Comment by quink-black** [comment]
是用surface做输入还是yuv420/nv12 buffer做输入？API调用还是ffmpeg cmd调用？

**Comment by zhubinsheng** [comment]
yuv420 ffmpeg cmd调用 
我[这样改](https://github.com/zhubinsheng/FFmpeg/commit/b2054aaae2a9e271fdaa06ec0581fd27bb915325)了一下就没问题了

还有兼容性问题 一些小米手机上不支持COLOR_FormatYUV420Planar = 0x13，但他们支持COLOR_FormatYUV420SemiPlanar                          = 0x15,

**Comment by quink-black** [comment]
> 这样改

看下ffmpeg现在的代码，不需要修改。

COLOR_FormatYUV420SemiPlanar = 0x15也没问题，已经支持了。
